name: CI/CD Pipeline
# test, build, stage, and deploy our code
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Format code with Black
      run: |
        pip install black
        black .

    - name: Run tests
      run: |
        pip install pytest
        pytest

  # merge:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/develop'

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Merge develop into main
  #     run: |
  #       git config --global user.name 'github-actions'
  #       git config --global user.email 'github-actions@github.com'
  #       git checkout main
  #       git merge develop
  #       git push origin main
