name: CI Pipeline
# test, build, stage, and deploy our code
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Setup and Build Hardware Component
      run: |
        cd hardware/code/libraries/buildhat++
        sudo apt install libserial-dev -y
        cmake .
        cmake --build .
        
    - name: Format code with Black
      run: |
        pip install black
        black .

    - name: Run tests
      run: |
        pip install pytest
        pytest

  # merge:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/develop'

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 0  # Fetch all history for all branches

  #   - name: Merge develop into main
  #     run: |
  #       git config --global user.name 'github-actions'
  #       git config --global user.email 'github-actions@github.com'
  #       git fetch --all 
  #       git checkout main  
  #       git merge develop
  #       git push origin main